import {
  buildContributionImpact,
  buildForwardIncomeProjection,
  buildIncomeSnowball,
  calculateHouseholdMetrics,
  flattenHoldings,
  formatCurrency,
  formatCurrencyPrecise,
  formatMultiple,
  formatPercent,
  groupIncomeByAccount,
  groupIncomeByCategory,
  groupIncomeByOwner,
} from '../data/mockData'
import { Panel } from '../ui/Panel'
import { StatCard } from '../ui/StatCard'
import { SectionNav } from './SectionNav'

const dashboardSections = [
  { id: 'dashboard-overview', label: 'Overview' },
  { id: 'dashboard-income-engine', label: 'Income Engine' },
  { id: 'dashboard-fire-tracker', label: 'FIRE Tracker' },
  { id: 'dashboard-accounts-breakdown', label: 'Accounts Breakdown' },
]

export function DashboardPage({ accounts = [], cashFlow = { expenses: [] } }) {
  const metrics = calculateHouseholdMetrics(accounts, cashFlow)
  const holdings = flattenHoldings(accounts)
  const forwardProjection = buildForwardIncomeProjection(accounts, 12)
  const strategyGroups = groupIncomeByCategory(accounts)
  const ownerIncomeGroups = groupIncomeByOwner(accounts)
  const accountIncomeGroups = groupIncomeByAccount(accounts)
  const contributionImpact = buildContributionImpact(metrics)
  const snowball = buildIncomeSnowball(metrics)
  const maxForwardIncome = Math.max(...forwardProjection.points.map((point) => point.total), 1)

  const summaryCards = [
    {
      title: 'Monthly portfolio income',
      value: formatCurrencyPrecise(metrics.monthlyPortfolioIncome),
      change: formatCurrency(metrics.annualPortfolioIncome),
      detail: 'Current passive income run-rate across all holdings, accounts, and owners.',
    },
    {
      title: 'Annual portfolio income',
      value: formatCurrency(metrics.annualPortfolioIncome),
      change: `${metrics.holdingsCount} holdings`,
      detail: 'Forward annual income estimate using each position’s yield profile and market value.',
    },
    {
      title: 'Weighted portfolio yield',
      value: formatPercent(metrics.weightedPortfolioYield),
      change: formatCurrency(metrics.portfolioMarketValue),
      detail: 'Blended current yield generated by the portfolio income engine.',
    },
    {
      title: 'Yield on cost',
      value: formatPercent(metrics.yieldOnCost),
      change: formatCurrency(metrics.totalCostBasis),
      detail: 'Annual income divided by total capital invested across current positions.',
    },
    {
      title: 'Income coverage ratio',
      value: formatMultiple(metrics.incomeCoverageRatio),
      change: formatCurrency(metrics.monthlyHouseholdExpenses),
      detail: 'Monthly portfolio income coverage of current household expenses.',
    },
    {
      title: 'Contribution conversion',
      value: `${formatCurrencyPrecise(metrics.contributionToIncomeConversion)}/yr`,
      change: 'per $1k invested',
      detail: 'Estimated annual income added for every incremental $1,000 invested at today’s weighted yield.',
    },
  ]

  return (
    <div className="space-y-8">
      <div>
        <p className="text-sm uppercase tracking-[0.3em] text-brand-300">Portfolio Intelligence</p>
        <h2 className="mt-2 text-4xl font-semibold text-white">Portfolio Income Engine</h2>
        <p className="mt-3 max-w-3xl text-slate-400">
          WealthOS now runs as a premium income analysis platform with owner-aware yield intelligence, forward income
          forecasting, strategy segmentation, contribution modeling, and reinvestment snowball visibility.
        </p>
      </div>

      <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
        {summaryCards.map((card) => (
          <StatCard key={card.title} {...card} />
        ))}
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.25fr,0.75fr]">
        <Panel className="overflow-hidden">
          <SectionHeader
            eyebrow="Forward Income Projection"
            title="12-month forward income map"
            description="Monthly portfolio cash flow estimate with uneven distribution support for quarterly-paying positions."
            badge={`Annual total ${formatCurrency(forwardProjection.annualTotal)}`}
          />

          <div className="mt-8 grid gap-6 xl:grid-cols-[1.35fr,0.85fr]">
            <div className="rounded-3xl border border-slate-800 bg-slate-950/60 p-5">
              <div className="flex h-72 items-end gap-3">
                {forwardProjection.points.map((point) => (
                  <div key={point.label} className="flex flex-1 flex-col items-center justify-end gap-3">
                    <div className="flex h-full w-full items-end">
                      <div
                        className="relative w-full overflow-hidden rounded-t-[1.5rem] border border-brand-400/10 bg-gradient-to-t from-brand-500 via-brand-400 to-cyan-300 shadow-lg shadow-brand-500/20"
                        style={{ height: `${Math.max((point.total / maxForwardIncome) * 100, 12)}%` }}
                      >
                        <div className="absolute inset-x-0 top-0 h-10 bg-white/10" />
                      </div>
                    </div>
                    <div className="text-center">
                      <p className="text-[11px] uppercase tracking-[0.18em] text-slate-500">{point.label}</p>
                      <p className="mt-1 text-xs font-medium text-slate-100">{formatCurrencyPrecise(point.total)}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="space-y-4">
              <MetricPill label="Monthly average" value={formatCurrencyPrecise(metrics.monthlyPortfolioIncome)} />
              <MetricPill
                label="Peak month"
                value={formatCurrencyPrecise(Math.max(...forwardProjection.points.map((point) => point.total)))}
              />
              <MetricPill
                label="Lightest month"
                value={formatCurrencyPrecise(Math.min(...forwardProjection.points.map((point) => point.total)))}
              />
              <div className="rounded-3xl border border-slate-800 bg-slate-950/60 p-5">
                <p className="text-xs uppercase tracking-[0.2em] text-slate-500">Projection logic</p>
                <p className="mt-3 text-sm leading-7 text-slate-300">
                  Holdings with only annual yield use market value × annual yield % ÷ 12. Quarterly-paying seed data is
                  mapped into uneven monthly distributions so income seasonality is visible instead of flattened away.
                </p>
              </div>
            </div>
          </div>
        </Panel>
      </section>

        <Panel>
          <SectionHeader
            eyebrow="Contribution Impact"
            title="Contribution Impact"
            description="Weighted-yield conversion examples showing how fresh capital turns into future income."
          />
          <div className="mt-6 space-y-4">
            {contributionImpact.map((item) => (
              <div key={item.amount} className="rounded-3xl border border-slate-800 bg-slate-950/60 p-5">
                <div className="flex items-start justify-between gap-4">
                  <div>
                    <p className="text-sm uppercase tracking-[0.18em] text-slate-500">Contribution example</p>
                    <p className="mt-2 text-2xl font-semibold text-white">+{formatCurrency(item.amount)}</p>
                  </div>
                  <span className="rounded-full bg-brand-500/10 px-3 py-1 text-xs font-semibold text-brand-200">
                    {formatCurrencyPrecise(item.monthlyIncomeIncrease)}/mo
                  </span>
                </div>
                <p className="mt-4 text-sm text-slate-300">
                  {formatCurrency(item.amount)} per month compounds into approximately{' '}
                  <span className="font-semibold text-emerald-300">{formatCurrencyPrecise(item.annualIncomeIncrease)} annual income</span>
                  {' '}at the current weighted portfolio yield.
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section id="dashboard-fire-tracker" className="space-y-5 scroll-mt-28">
        <div className="flex flex-col gap-2">
          <p className="text-sm uppercase tracking-[0.24em] text-brand-300">FIRE Tracker</p>
          <h3 className="text-2xl font-semibold text-white">Passive income coverage against your target</h3>
          <p className="max-w-3xl text-sm leading-6 text-slate-400">
            Default monthly FIRE target is set to {formatCurrency(fireMetrics.monthlyTarget)} with live progress driven by current portfolio income.
          </p>
        </div>

        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
          <StatCard title="Target Monthly Income" value={formatCurrency(fireMetrics.monthlyTarget)} change="Default" detail="Baseline monthly FIRE cash-flow target." tone="slate" />
          <StatCard title="Current Passive Income" value={formatCurrencyPrecise(fireMetrics.currentPassiveIncome)} change={formatCurrency(fireMetrics.currentPassiveIncome * 12)} detail="Current monthly passive income from the portfolio." tone="brand" />
          <StatCard title="Coverage Ratio" value={formatPercent(fireMetrics.coverageRatio * 100)} change={`${fireMetrics.coverageRatio.toFixed(2)}x`} detail="Current passive income divided by the target monthly income." tone="emerald" />
          <StatCard title="Remaining Income Gap" value={formatCurrencyPrecise(fireMetrics.remainingIncomeGap)} change={formatCurrency(fireMetrics.remainingIncomeGap * 12)} detail="How much more monthly passive income is needed to hit FIRE." tone="slate" />
          <StatCard title="Annual FIRE Target" value={formatCurrency(fireMetrics.annualFireTarget)} change="12 months" detail="Annual target derived from the monthly FIRE target." tone="slate" />
        </div>

      <div className="grid gap-6 xl:grid-cols-[1.12fr,0.88fr]">
        <Panel>
          <SectionHeader
            eyebrow="Income by Strategy"
            title="Strategy bucket income mix"
            description="Each sleeve shows capital deployed, current income, weighted yield, and share of household passive income."
          />

          <div className="mt-6 overflow-hidden rounded-3xl border border-slate-800 bg-slate-950/50">
            <div className="grid grid-cols-[1.1fr,0.85fr,0.85fr,0.7fr] gap-4 border-b border-slate-800 px-5 py-4 text-xs uppercase tracking-[0.2em] text-slate-500 md:grid-cols-[1.1fr,0.8fr,0.8fr,0.8fr,0.7fr]">
              <p>Strategy</p>
              <p className="hidden md:block">Market value</p>
              <p>Monthly</p>
              <p>Annual</p>
              <p>Yield / share</p>
            </div>
            <div className="divide-y divide-slate-800">
              {strategyGroups.map((group) => {
                const incomeShare = metrics.annualPortfolioIncome ? (group.annualIncome / metrics.annualPortfolioIncome) * 100 : 0
                return (
                  <div
                    key={group.category}
                    className="grid grid-cols-[1.1fr,0.85fr,0.85fr,0.7fr] gap-4 px-5 py-4 text-sm md:grid-cols-[1.1fr,0.8fr,0.8fr,0.8fr,0.7fr]"
                  >
                    <div>
                      <p className="font-semibold text-white">{group.category}</p>
                      <div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-800">
                        <div
                          className="h-full rounded-full bg-gradient-to-r from-brand-400 to-emerald-300"
                          style={{ width: `${Math.max(incomeShare, 3)}%` }}
                        />
                      </div>
                    </div>
                    <p className="hidden font-medium text-slate-200 md:block">{formatCurrency(group.marketValue)}</p>
                    <p className="font-medium text-slate-200">{formatCurrencyPrecise(group.monthlyIncome)}</p>
                    <p className="font-medium text-slate-200">{formatCurrency(group.annualIncome)}</p>
                    <div>
                      <p className="font-medium text-brand-200">{formatPercent(group.weightedYield)}</p>
                      <p className="mt-1 text-xs text-slate-500">{formatPercent(incomeShare)} of income</p>
                    </div>
                  </div>
                )
              })}
            </div>
          </Panel>
        </div>

        <Panel>
          <SectionHeader
            eyebrow="Income by Owner"
            title="Passive income by owner"
            description="JR, Lisa, and Joint sleeves broken out by monthly and annual income contribution."
          />
          <div className="mt-6 space-y-4">
            {ownerIncomeGroups.map((group) => (
              <div key={group.owner} className="rounded-3xl border border-slate-800 bg-slate-950/60 p-5">
                <div className="flex items-start justify-between gap-4">
                  <div>
                    <p className="text-lg font-semibold text-white">{group.owner}</p>
                    <p className="mt-1 text-sm text-slate-400">{formatCurrencyPrecise(group.monthlyIncome)}/mo</p>
                  </div>
                  <span className="rounded-full bg-brand-500/10 px-3 py-1 text-xs font-semibold text-brand-200">
                    {formatPercent(group.passiveIncomeShare)}
                  </span>
                </div>
                <div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-800">
                  <div className="h-full rounded-full bg-gradient-to-r from-brand-400 to-emerald-300" style={{ width: `${Math.max(group.passiveIncomeShare, 4)}%` }} />
                </div>
                <div className="mt-4 grid gap-3 sm:grid-cols-2">
                  <MetricPill label="Annual income" value={formatCurrency(group.annualIncome)} />
                  <MetricPill label="Passive income share" value={formatPercent(group.passiveIncomeShare)} />
                </div>
              </div>
            ))}
          </div>
        </Panel>
      </div>

      <div className="grid gap-6 xl:grid-cols-[0.95fr,1.05fr]">
        <Panel>
          <SectionHeader
            eyebrow="Income Snowball"
            title="Reinvestment snowball outlook"
            description="Simple compounding model using recurring monthly contributions plus reinvested portfolio income."
          />

          <div className="mt-6 grid gap-4 sm:grid-cols-2">
            <SnowballCard label="Current annual income" value={formatCurrency(metrics.annualPortfolioIncome)} detail={formatCurrency(metrics.portfolioMarketValue)} />
            {snowball.map((item) => (
              <SnowballCard
                key={item.years}
                label={`Projected income in ${item.years} year${item.years > 1 ? 's' : ''}`}
                value={formatCurrency(item.annualIncome)}
                detail={`Portfolio ${formatCurrency(item.portfolioValue)}`}
              />
            ))}
          </div>
        </Panel>

        <Panel>
          <SectionHeader
            eyebrow="Income by Account"
            title="Account-level income engine"
            description="Current balance, owner, income, and weighted yield for every tracked account sleeve."
          />
          <div className="mt-6 space-y-4">
            {accountIncomeGroups.map((account) => (
              <div key={account.id} className="rounded-3xl border border-slate-800 bg-slate-950/60 p-5">
                <div className="flex flex-wrap items-start justify-between gap-4">
                  <div>
                    <p className="text-lg font-semibold text-white">{account.accountName}</p>
                    <p className="mt-1 text-sm text-slate-400">{account.owner}</p>
                  </div>
                  <span className="rounded-full border border-slate-700 px-3 py-1 text-xs uppercase tracking-[0.18em] text-slate-400">
                    {formatPercent(account.weightedYield)} weighted yield
                  </span>
                </div>
                <div className="mt-5 grid gap-3 sm:grid-cols-3">
                  <MetricPill label="Current balance" value={formatCurrency(account.currentBalance)} />
                  <MetricPill label="Monthly income" value={formatCurrencyPrecise(account.monthlyIncome)} />
                  <MetricPill label="Annual income" value={formatCurrency(account.annualIncome)} />
                </div>
              </div>
            ))}
          </div>
        </Panel>
      </section>
    </div>
  )
}

      <Panel>
        <SectionHeader
          eyebrow="Holdings Detail"
          title="Premium holdings detail"
          description="Expanded holding analytics with owner, strategy, yield, cost basis, and account context across the full household portfolio."
          badge={`${holdings.length} holdings`}
        />

        <div className="mt-6 space-y-4 lg:hidden">
          {holdings.map((holding) => (
            <HoldingCard key={holding.id} holding={holding} />
          ))}
        </div>

        <div className="mt-6 hidden overflow-x-auto rounded-3xl border border-slate-800 bg-slate-950/50 lg:block">
          <table className="min-w-full divide-y divide-slate-800 text-left text-sm">
            <thead className="bg-slate-950/90 text-xs uppercase tracking-[0.2em] text-slate-500">
              <tr>
                <th className="px-5 py-4 font-medium">Ticker</th>
                <th className="px-5 py-4 font-medium">Holding</th>
                <th className="px-5 py-4 font-medium">Owner</th>
                <th className="px-5 py-4 font-medium">Account</th>
                <th className="px-5 py-4 font-medium">Strategy</th>
                <th className="px-5 py-4 font-medium">Market value</th>
                <th className="px-5 py-4 font-medium">Cost basis</th>
                <th className="px-5 py-4 font-medium">Annual yield</th>
                <th className="px-5 py-4 font-medium">Monthly income</th>
                <th className="px-5 py-4 font-medium">Annual income</th>
                <th className="px-5 py-4 font-medium">Yield on cost</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800 text-sm">
              {holdings.map((holding) => (
                <tr key={holding.id} className="transition-colors hover:bg-slate-900/80">
                  <td className="px-5 py-4 font-semibold text-white">{holding.ticker}</td>
                  <td className="px-5 py-4 text-slate-200">{holding.holdingName}</td>
                  <td className="px-5 py-4 text-slate-300">{holding.owner}</td>
                  <td className="px-5 py-4 text-slate-300">{holding.accountName}</td>
                  <td className="px-5 py-4 text-slate-300">{holding.category}</td>
                  <td className="px-5 py-4 text-slate-200">{formatCurrency(holding.marketValue)}</td>
                  <td className="px-5 py-4 text-slate-200">{formatCurrency(holding.costBasis)}</td>
                  <td className="px-5 py-4 text-brand-200">{formatPercent(holding.annualYieldPercent)}</td>
                  <td className="px-5 py-4 text-slate-200">{formatCurrencyPrecise(holding.monthlyIncome)}</td>
                  <td className="px-5 py-4 text-emerald-300">{formatCurrency(holding.annualIncome)}</td>
                  <td className="px-5 py-4 text-slate-200">{formatPercent(holding.yieldOnCostPercent)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Panel>
    </div>
  )
}

function SectionHeader({ eyebrow, title, description, badge }) {
  return (
    <div className="flex flex-wrap items-start justify-between gap-4">
      <div>
        <p className="text-sm uppercase tracking-[0.25em] text-brand-300">{eyebrow}</p>
        <h3 className="mt-2 text-2xl font-semibold text-white">{title}</h3>
        <p className="mt-2 max-w-3xl text-sm text-slate-400">{description}</p>
      </div>
      {badge ? (
        <span className="rounded-full border border-slate-700 px-3 py-1 text-xs uppercase tracking-[0.2em] text-slate-400">
          {badge}
        </span>
      ) : null}
    </div>
  )
}

function MetricPill({ label, value }) {
  return (
    <div className="rounded-2xl border border-slate-800 bg-slate-900/60 px-4 py-3">
      <p className="text-xs uppercase tracking-[0.18em] text-slate-500">{label}</p>
      <p className="mt-2 text-base font-semibold text-white sm:text-lg">{value}</p>
    </div>
  )
}

function SnowballCard({ label, value, detail }) {
  return (
    <div className="rounded-3xl border border-slate-800 bg-slate-950/60 p-5">
      <p className="text-xs uppercase tracking-[0.18em] text-slate-500">{label}</p>
      <p className="mt-3 text-3xl font-semibold text-white">{value}</p>
      <p className="mt-2 text-sm text-slate-400">{detail}</p>
    </div>
  )
}

function HoldingCard({ holding }) {
  return (
    <div className="rounded-3xl border border-slate-800 bg-slate-950/60 p-5">
      <div className="flex items-start justify-between gap-4">
        <div>
          <p className="text-lg font-semibold text-white">{holding.ticker}</p>
          <p className="mt-1 text-sm text-slate-400">{holding.holdingName}</p>
        </div>
        <span className="rounded-full bg-brand-500/10 px-3 py-1 text-xs font-semibold text-brand-200">{holding.category}</span>
      </div>
      <div className="mt-5 grid grid-cols-2 gap-3 text-sm">
        <HoldingField label="Owner" value={holding.owner} />
        <HoldingField label="Account" value={holding.accountName} />
        <HoldingField label="Market value" value={formatCurrency(holding.marketValue)} />
        <HoldingField label="Cost basis" value={formatCurrency(holding.costBasis)} />
        <HoldingField label="Annual yield" value={formatPercent(holding.annualYieldPercent)} />
        <HoldingField label="Monthly income" value={formatCurrencyPrecise(holding.monthlyIncome)} />
        <HoldingField label="Annual income" value={formatCurrency(holding.annualIncome)} />
        <HoldingField label="Yield on cost" value={formatPercent(holding.yieldOnCostPercent)} />
      </div>
    </div>
  )
}

function HoldingField({ label, value }) {
  return (
    <div className="rounded-2xl border border-slate-800 bg-slate-900/60 px-4 py-3">
      <p className="text-[11px] uppercase tracking-[0.16em] text-slate-500">{label}</p>
      <p className="mt-2 font-medium text-slate-100">{value}</p>
    </div>
  )
}
